import sys

from functools import partial

# | Byte        | Register    | Purpose                      |
# | address     | number      |                              |
# | ----------- | ----------- | ---------------------------- |
# | 0x000–0x0ff | 0x000–0x03f | 64 general purpose registers |
# | 0x100–0x1ff | 0x040–0x07f | 64 matrix bias registers     |
# | 0x200–0x2ff | 0x080–0x0bf | 64 feedback registers        |
# | 0x300–0x3ff | 0x0c0–0x0ff | 64 matrix output registers   |
# | 0x400–0x7ff | 0x100–0x0ff | 64×4 matrix connections      |

# Feedback registers are outputs from modules that can be fed back
# into mod matrix calculations
#
# They're laid out roughly as follows:
#  0x80–0x8f  global/misc (osc outputs? filter output??)
#  0xa0–0xaf  envelope outputs
#  0x90–0x9f  lfo outputs
#  0xb0–0xbf  anything else

# Bias registers are a convenience for modulations (matrix outputs)
# where the thing being modulated is a control input (e.g. filter
# cutoff).  The matrix is initialized by default with each bias input
# as the first cell in each output row at 100% level, so e.g.  the
# filter cutoff is 100% controlled by the filter cutoff bias register
# if that row has no other modulations.  This isn't mandatory, you can
# edit the cell to disconnect that matrix row from its bias register,
# and then that bias register is just general purpose.  TL;dr the
# general purpose registers vs matrix bias registers distinction is by
# convention, not baked into the architecture like the other categories.

inputs_feedbacks = {
    0x80: "VoicePitch",

    0x90: "Env1Output",
    0x91: "Env2Output",

    0xa0: "LFO1Output",
    0xa1: "LFO2Output",

    # Osc1Output
    # Osc2Output
    # NoiseOutput
    # RingModOutput
    # S&H output??"
    # Filt1Output
}

matrix_outputs = []
# 4×4 oscillators = 16
for i in range(1, 5):
    for dst in ("Pitch", "Shape", "Level", "Extra"):
        matrix_outputs.append(f"Osc{i}{dst}")

# 4×2 filters = 8
inputs_feedbacks[len(matrix_outputs)] = "Filt1Mode"
matrix_outputs.extend(("Filt1Cutoff", "Filt1Resonance"))
matrix_outputs.extend([""] * 6)

# 8 empty slots (other input things.. noise, S&H, pre-filter effects (drive)
matrix_outputs.extend([""] * 8)

# 4×4 envelopes = 16
for i in range(1, 5):
    for dst in ("Attack", "Decay", "Sustain", "Release"):
        matrix_outputs.append(f"Env{i}{dst}")

# 4×2 LFOs = 8
for i in range(1, 5):
    for dst in ("Rate", "Level"):
        matrix_outputs.append(f"LFO{i}{dst}")

# 8 empty slots (effects)
matrix_outputs.extend([""] * 8)
assert len(matrix_outputs) == 64

registers = [f"register{i:02X}" for i in range(256)]
for dst in range(64):
    for src in range(4):
        registers.append(f"matrix{dst:02X}Src{src}")

for i, src in inputs_feedbacks.items():
    registers[i] = src

for i, dst in enumerate(matrix_outputs):
    if not dst or dst[3] in "34" or dst.endswith("Extra"):
        continue  # leave gaps in the address space

    registers[0x40+i] = dst  # the input from the knob/whatever
    registers[0xc0+i] = f"Modulated{dst}"  # the one we calculate
    for j in range(4):
        registers[256+i*4+j] = f"{dst}Src{j}"

sections = {
    0x00: "64 general purpose registers (editable)",
    0x40: "64 mod matrix output bias registers (editable)",
    0x80: "64 feedback registers (updated during [Engine.Fill])",
    0xc0: "64 mod matrix outputs (calculated as read)",
    0x100: "64×4 mod matrix cells (editable)",
}

truncations = {
    "Cutoff": "Cut",
    "Resonance": "Res",
    "Attack": "Atk",
    "Sustain": "Sust",
    "Release": "Rel",
}

def short_name_for(name):
    if not name[0].isupper():
        return ""
    name, _, src = name.partition("Src")
    if src:
        name = name.replace("Decay", "Dec")
    for a, b in truncations.items():
        name = name.replace(a, b)
    for i in range(3, 5):
        if not name[i].isdigit():
            continue
        name = f"{name[:i+1]} {name[i+1:]}"
        break
    return name

command = " ".join(["python"] + sys.argv)
with open("register-table.go", "w") as fp:
    print = partial(print, file=fp)
    print(f"// Code generated by {command}; DO NOT EDIT.")
    print()
    print("package picosynth")
    print()
    print("const (")
    extra = " = iota"
    for i, register in enumerate(registers):
        if i and not i%16:
            print()
        if (comment := sections.get(i)):
            print(f"\t// {comment}")
        print(f"\t{register}{extra}")
        extra = ""
    print()
    print("\tNumRegisters")
    print(")")
    print()
    print("// RegisterNames contains the names of all assigned registers.")
    print("var RegisterNames = []string{")
    for i, register in enumerate(registers):
        if not i%16:
            if i:
                print()
            print(f"\t// 0x{i:02X}..0x{i+15:02X}")

        print(f'\t"{short_name_for(register)}",')
    print("}")
