//go:build ignore

package main

import (
	"fmt"
	"log"
	"math"
	"os"
)

const (
	SignalBits    = 32
	MinSignal     = math.MinInt32
	MaxSignal     = math.MaxInt32
	Log2TableSize = 6 // make as small as possible to still pass tests
	TableSize     = 1 << Log2TableSize
	WrapShift     = SignalBits - Log2TableSize
)

type Signal int32

func main() {
	fp, err := os.Create("sine-table.go")
	if err != nil {
		log.Fatal(err)
	}
	defer fp.Close()

	fmt.Fprintf(
		fp,
		"%s\n\n%s\n\n%s\n%s\n",
		"// Code generated by go run make-sine-table.go; DO NOT EDIT.",
		"package picosynth",
		"// SineTable is a [Wavetable] approximating a sine wave.",
		"var SineTable = Wavetable{")

	for i := range TableSize {
		xs := Signal(i << WrapShift)
		x := 2 * math.Pi * float64(xs>>WrapShift) / TableSize
		v := Signal(min(math.Sin(x)*(-MinSignal), MaxSignal))
		fmt.Fprintf(fp, "\t%d,\n", v)
	}
	fmt.Fprintln(fp, "}")
}
