//go:build ignore

package main

import (
	"fmt"
	"log"
	"math"
	"math/bits"
	"os"
)

const (
	SampleRate  = 48000
	TableOctave = 10   // make as big as possible without overflow
	TableSize   = 1024 // make as small as possible to still pass tests
)

func main() {
	tableSizeShift := bits.Len(TableSize) - 1
	if (1 << tableSizeShift) != TableSize {
		log.Fatal("not a power of 2")
	}

	fp, err := os.Create("frequency-table.go")
	if err != nil {
		log.Fatal(err)
	}
	defer fp.Close()

	fmt.Fprintf(
		fp,
		"%s\n\n%s\n\n%s\n",
		"// Code generated by go run make-frequency-table.go; DO NOT EDIT.",
		"package picosynth",
		"const (",
	)

	fmt.Fprintf(fp, "\tp2fTableOctave   = %d\n", TableOctave)
	fmt.Fprintf(fp, "\tlog2p2fTableSize = %d\n", tableSizeShift)

	fmt.Fprintln(fp, ")\n\nvar pitchToFrequencyTable = []uint32{")

	for i := range TableSize {
		note := (TableOctave + float64(i)/TableSize) * 12
		freqHz := 440 * math.Pow(2, float64(note-69)/12)
		freq := uint32(freqHz * float64(1<<32) / SampleRate)
		fmt.Fprintf(fp, "\t0x%08x,\n", freq)
	}
	fmt.Fprintln(fp, "}")
}
