// Code generated by python make-register-table.py; DO NOT EDIT.

package picosynth

const (
	// 64 general purpose registers (editable)
	register00 = iota
	register01
	register02
	register03
	register04
	register05
	register06
	register07
	register08
	register09
	register0A
	register0B
	register0C
	register0D
	register0E
	register0F

	register10
	register11
	register12
	register13
	register14
	register15
	register16
	register17
	register18
	register19
	register1A
	register1B
	register1C
	register1D
	register1E
	register1F

	register20
	register21
	register22
	register23
	register24
	register25
	register26
	register27
	register28
	register29
	register2A
	register2B
	register2C
	register2D
	register2E
	register2F

	register30
	register31
	register32
	register33
	register34
	register35
	register36
	register37
	register38
	register39
	register3A
	register3B
	register3C
	register3D
	register3E
	register3F

	// 64 mod matrix output bias registers (editable)
	Osc1Pitch
	Osc1Shape
	Osc1Level
	register43
	Osc2Pitch
	Osc2Shape
	Osc2Level
	register47
	register48
	register49
	register4A
	register4B
	register4C
	register4D
	register4E
	register4F

	FilterCutoff
	FilterResonance
	register52
	register53
	register54
	register55
	register56
	register57
	register58
	register59
	register5A
	register5B
	register5C
	register5D
	register5E
	register5F

	Env1Attack
	Env1Decay
	Env1Sustain
	Env1Release
	Env2Attack
	Env2Decay
	Env2Sustain
	Env2Release
	register68
	register69
	register6A
	register6B
	register6C
	register6D
	register6E
	register6F

	LFO1Rate
	LFO1Level
	LFO2Rate
	LFO2Level
	register74
	register75
	register76
	register77
	register78
	register79
	register7A
	register7B
	register7C
	register7D
	register7E
	register7F

	// 64 feedback registers (updated during [Engine.Fill])
	VoicePitch
	register81
	register82
	register83
	register84
	register85
	register86
	register87
	register88
	register89
	register8A
	register8B
	register8C
	register8D
	register8E
	register8F

	Env1Output
	Env2Output
	register92
	register93
	register94
	register95
	register96
	register97
	register98
	register99
	register9A
	register9B
	register9C
	register9D
	register9E
	register9F

	LFO1Output
	LFO2Output
	registerA2
	registerA3
	registerA4
	registerA5
	registerA6
	registerA7
	registerA8
	registerA9
	registerAA
	registerAB
	registerAC
	registerAD
	registerAE
	registerAF

	registerB0
	registerB1
	registerB2
	registerB3
	registerB4
	registerB5
	registerB6
	registerB7
	registerB8
	registerB9
	registerBA
	registerBB
	registerBC
	registerBD
	registerBE
	registerBF

	// 64 mod matrix outputs (calculated as read)
	ModulatedOsc1Pitch
	ModulatedOsc1Shape
	ModulatedOsc1Level
	registerC3
	ModulatedOsc2Pitch
	ModulatedOsc2Shape
	ModulatedOsc2Level
	registerC7
	registerC8
	registerC9
	registerCA
	registerCB
	registerCC
	registerCD
	registerCE
	registerCF

	ModulatedFilterCutoff
	ModulatedFilterResonance
	registerD2
	registerD3
	registerD4
	registerD5
	registerD6
	registerD7
	registerD8
	registerD9
	registerDA
	registerDB
	registerDC
	registerDD
	registerDE
	registerDF

	ModulatedEnv1Attack
	ModulatedEnv1Decay
	ModulatedEnv1Sustain
	ModulatedEnv1Release
	ModulatedEnv2Attack
	ModulatedEnv2Decay
	ModulatedEnv2Sustain
	ModulatedEnv2Release
	registerE8
	registerE9
	registerEA
	registerEB
	registerEC
	registerED
	registerEE
	registerEF

	ModulatedLFO1Rate
	ModulatedLFO1Level
	ModulatedLFO2Rate
	ModulatedLFO2Level
	registerF4
	registerF5
	registerF6
	registerF7
	registerF8
	registerF9
	registerFA
	registerFB
	registerFC
	registerFD
	registerFE
	registerFF

	// 64×4 mod matrix cells (editable)
	Osc1PitchSrc0
	Osc1PitchSrc1
	Osc1PitchSrc2
	Osc1PitchSrc3
	Osc1ShapeSrc0
	Osc1ShapeSrc1
	Osc1ShapeSrc2
	Osc1ShapeSrc3
	Osc1LevelSrc0
	Osc1LevelSrc1
	Osc1LevelSrc2
	Osc1LevelSrc3
	matrix03Src0
	matrix03Src1
	matrix03Src2
	matrix03Src3

	Osc2PitchSrc0
	Osc2PitchSrc1
	Osc2PitchSrc2
	Osc2PitchSrc3
	Osc2ShapeSrc0
	Osc2ShapeSrc1
	Osc2ShapeSrc2
	Osc2ShapeSrc3
	Osc2LevelSrc0
	Osc2LevelSrc1
	Osc2LevelSrc2
	Osc2LevelSrc3
	matrix07Src0
	matrix07Src1
	matrix07Src2
	matrix07Src3

	matrix08Src0
	matrix08Src1
	matrix08Src2
	matrix08Src3
	matrix09Src0
	matrix09Src1
	matrix09Src2
	matrix09Src3
	matrix0ASrc0
	matrix0ASrc1
	matrix0ASrc2
	matrix0ASrc3
	matrix0BSrc0
	matrix0BSrc1
	matrix0BSrc2
	matrix0BSrc3

	matrix0CSrc0
	matrix0CSrc1
	matrix0CSrc2
	matrix0CSrc3
	matrix0DSrc0
	matrix0DSrc1
	matrix0DSrc2
	matrix0DSrc3
	matrix0ESrc0
	matrix0ESrc1
	matrix0ESrc2
	matrix0ESrc3
	matrix0FSrc0
	matrix0FSrc1
	matrix0FSrc2
	matrix0FSrc3

	FilterCutoffSrc0
	FilterCutoffSrc1
	FilterCutoffSrc2
	FilterCutoffSrc3
	FilterResonanceSrc0
	FilterResonanceSrc1
	FilterResonanceSrc2
	FilterResonanceSrc3
	matrix12Src0
	matrix12Src1
	matrix12Src2
	matrix12Src3
	matrix13Src0
	matrix13Src1
	matrix13Src2
	matrix13Src3

	matrix14Src0
	matrix14Src1
	matrix14Src2
	matrix14Src3
	matrix15Src0
	matrix15Src1
	matrix15Src2
	matrix15Src3
	matrix16Src0
	matrix16Src1
	matrix16Src2
	matrix16Src3
	matrix17Src0
	matrix17Src1
	matrix17Src2
	matrix17Src3

	matrix18Src0
	matrix18Src1
	matrix18Src2
	matrix18Src3
	matrix19Src0
	matrix19Src1
	matrix19Src2
	matrix19Src3
	matrix1ASrc0
	matrix1ASrc1
	matrix1ASrc2
	matrix1ASrc3
	matrix1BSrc0
	matrix1BSrc1
	matrix1BSrc2
	matrix1BSrc3

	matrix1CSrc0
	matrix1CSrc1
	matrix1CSrc2
	matrix1CSrc3
	matrix1DSrc0
	matrix1DSrc1
	matrix1DSrc2
	matrix1DSrc3
	matrix1ESrc0
	matrix1ESrc1
	matrix1ESrc2
	matrix1ESrc3
	matrix1FSrc0
	matrix1FSrc1
	matrix1FSrc2
	matrix1FSrc3

	Env1AttackSrc0
	Env1AttackSrc1
	Env1AttackSrc2
	Env1AttackSrc3
	Env1DecaySrc0
	Env1DecaySrc1
	Env1DecaySrc2
	Env1DecaySrc3
	Env1SustainSrc0
	Env1SustainSrc1
	Env1SustainSrc2
	Env1SustainSrc3
	Env1ReleaseSrc0
	Env1ReleaseSrc1
	Env1ReleaseSrc2
	Env1ReleaseSrc3

	Env2AttackSrc0
	Env2AttackSrc1
	Env2AttackSrc2
	Env2AttackSrc3
	Env2DecaySrc0
	Env2DecaySrc1
	Env2DecaySrc2
	Env2DecaySrc3
	Env2SustainSrc0
	Env2SustainSrc1
	Env2SustainSrc2
	Env2SustainSrc3
	Env2ReleaseSrc0
	Env2ReleaseSrc1
	Env2ReleaseSrc2
	Env2ReleaseSrc3

	matrix28Src0
	matrix28Src1
	matrix28Src2
	matrix28Src3
	matrix29Src0
	matrix29Src1
	matrix29Src2
	matrix29Src3
	matrix2ASrc0
	matrix2ASrc1
	matrix2ASrc2
	matrix2ASrc3
	matrix2BSrc0
	matrix2BSrc1
	matrix2BSrc2
	matrix2BSrc3

	matrix2CSrc0
	matrix2CSrc1
	matrix2CSrc2
	matrix2CSrc3
	matrix2DSrc0
	matrix2DSrc1
	matrix2DSrc2
	matrix2DSrc3
	matrix2ESrc0
	matrix2ESrc1
	matrix2ESrc2
	matrix2ESrc3
	matrix2FSrc0
	matrix2FSrc1
	matrix2FSrc2
	matrix2FSrc3

	LFO1RateSrc0
	LFO1RateSrc1
	LFO1RateSrc2
	LFO1RateSrc3
	LFO1LevelSrc0
	LFO1LevelSrc1
	LFO1LevelSrc2
	LFO1LevelSrc3
	LFO2RateSrc0
	LFO2RateSrc1
	LFO2RateSrc2
	LFO2RateSrc3
	LFO2LevelSrc0
	LFO2LevelSrc1
	LFO2LevelSrc2
	LFO2LevelSrc3

	matrix34Src0
	matrix34Src1
	matrix34Src2
	matrix34Src3
	matrix35Src0
	matrix35Src1
	matrix35Src2
	matrix35Src3
	matrix36Src0
	matrix36Src1
	matrix36Src2
	matrix36Src3
	matrix37Src0
	matrix37Src1
	matrix37Src2
	matrix37Src3

	matrix38Src0
	matrix38Src1
	matrix38Src2
	matrix38Src3
	matrix39Src0
	matrix39Src1
	matrix39Src2
	matrix39Src3
	matrix3ASrc0
	matrix3ASrc1
	matrix3ASrc2
	matrix3ASrc3
	matrix3BSrc0
	matrix3BSrc1
	matrix3BSrc2
	matrix3BSrc3

	matrix3CSrc0
	matrix3CSrc1
	matrix3CSrc2
	matrix3CSrc3
	matrix3DSrc0
	matrix3DSrc1
	matrix3DSrc2
	matrix3DSrc3
	matrix3ESrc0
	matrix3ESrc1
	matrix3ESrc2
	matrix3ESrc3
	matrix3FSrc0
	matrix3FSrc1
	matrix3FSrc2
	matrix3FSrc3

	NumRegisters
)

// RegisterNames contains the names of all assigned registers.
var RegisterNames = []string{
	// 0x00..0x0F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x10..0x1F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x20..0x2F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x30..0x3F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x40..0x4F
	"Osc1 Pitch",
	"Osc1 Shape",
	"Osc1 Level",
	"",
	"Osc2 Pitch",
	"Osc2 Shape",
	"Osc2 Level",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x50..0x5F
	"Filter Cut",
	"Filter Res",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x60..0x6F
	"Env1 Atk",
	"Env1 Decay",
	"Env1 Sust",
	"Env1 Rel",
	"Env2 Atk",
	"Env2 Decay",
	"Env2 Sust",
	"Env2 Rel",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x70..0x7F
	"LFO1 Rate",
	"LFO1 Level",
	"LFO2 Rate",
	"LFO2 Level",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x80..0x8F
	"VoicePitch",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x90..0x9F
	"Env1 Output",
	"Env2 Output",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0xA0..0xAF
	"LFO1 Output",
	"LFO2 Output",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0xB0..0xBF
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0xC0..0xCF
	"ModulatedOsc1Pitch",
	"ModulatedOsc1Shape",
	"ModulatedOsc1Level",
	"",
	"ModulatedOsc2Pitch",
	"ModulatedOsc2Shape",
	"ModulatedOsc2Level",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0xD0..0xDF
	"ModulatedFilter Cut",
	"ModulatedFilter Res",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0xE0..0xEF
	"ModulatedEnv1Atk",
	"ModulatedEnv1Decay",
	"ModulatedEnv1Sust",
	"ModulatedEnv1Rel",
	"ModulatedEnv2Atk",
	"ModulatedEnv2Decay",
	"ModulatedEnv2Sust",
	"ModulatedEnv2Rel",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0xF0..0xFF
	"ModulatedLFO1Rate",
	"ModulatedLFO1Level",
	"ModulatedLFO2Rate",
	"ModulatedLFO2Level",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x100..0x10F
	"Osc1 Pitch",
	"Osc1 Pitch",
	"Osc1 Pitch",
	"Osc1 Pitch",
	"Osc1 Shape",
	"Osc1 Shape",
	"Osc1 Shape",
	"Osc1 Shape",
	"Osc1 Level",
	"Osc1 Level",
	"Osc1 Level",
	"Osc1 Level",
	"",
	"",
	"",
	"",

	// 0x110..0x11F
	"Osc2 Pitch",
	"Osc2 Pitch",
	"Osc2 Pitch",
	"Osc2 Pitch",
	"Osc2 Shape",
	"Osc2 Shape",
	"Osc2 Shape",
	"Osc2 Shape",
	"Osc2 Level",
	"Osc2 Level",
	"Osc2 Level",
	"Osc2 Level",
	"",
	"",
	"",
	"",

	// 0x120..0x12F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x130..0x13F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x140..0x14F
	"Filter Cut",
	"Filter Cut",
	"Filter Cut",
	"Filter Cut",
	"Filter Res",
	"Filter Res",
	"Filter Res",
	"Filter Res",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x150..0x15F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x160..0x16F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x170..0x17F
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x180..0x18F
	"Env1 Atk",
	"Env1 Atk",
	"Env1 Atk",
	"Env1 Atk",
	"Env1 Dec",
	"Env1 Dec",
	"Env1 Dec",
	"Env1 Dec",
	"Env1 Sust",
	"Env1 Sust",
	"Env1 Sust",
	"Env1 Sust",
	"Env1 Rel",
	"Env1 Rel",
	"Env1 Rel",
	"Env1 Rel",

	// 0x190..0x19F
	"Env2 Atk",
	"Env2 Atk",
	"Env2 Atk",
	"Env2 Atk",
	"Env2 Dec",
	"Env2 Dec",
	"Env2 Dec",
	"Env2 Dec",
	"Env2 Sust",
	"Env2 Sust",
	"Env2 Sust",
	"Env2 Sust",
	"Env2 Rel",
	"Env2 Rel",
	"Env2 Rel",
	"Env2 Rel",

	// 0x1A0..0x1AF
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x1B0..0x1BF
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x1C0..0x1CF
	"LFO1 Rate",
	"LFO1 Rate",
	"LFO1 Rate",
	"LFO1 Rate",
	"LFO1 Level",
	"LFO1 Level",
	"LFO1 Level",
	"LFO1 Level",
	"LFO2 Rate",
	"LFO2 Rate",
	"LFO2 Rate",
	"LFO2 Rate",
	"LFO2 Level",
	"LFO2 Level",
	"LFO2 Level",
	"LFO2 Level",

	// 0x1D0..0x1DF
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x1E0..0x1EF
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",

	// 0x1F0..0x1FF
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
}
