echo "// Code generated by $0; DO NOT EDIT." > pio_emulated.go
sed -e 's,//go:build pico,//go:build !baremetal,' \
    -e 's,import "github.com/tinygo-org/pio/rp2-pio",import pio "gbenson.net/go/picosynth/x/emulator",' \
    < pio_pico.go \
    >> pio_emulated.go
