// Code generated by make-pio-emulated.sh; DO NOT EDIT.
//go:build !baremetal

package pio

import pio "gbenson.net/go/picosynth/x/emulator"

type StateMachine = pio.StateMachine

var (
	PIO0 = pio.PIO0
	PIO1 = pio.PIO1
)
