// Code generated by make-machine-emulated.sh; DO NOT EDIT.
//go:build !baremetal

package machine

import machine "gbenson.net/go/picosynth/x/emulator"

type (
	ADC       = machine.ADC
	ADCConfig = machine.ADCConfig

	Pin       = machine.Pin
	PinConfig = machine.PinConfig
)

const (
	ADC0 = machine.ADC0
	ADC1 = machine.ADC1
	ADC2 = machine.ADC2
	ADC3 = machine.ADC3

	GP0  = machine.GP0
	GP1  = machine.GP1
	GP2  = machine.GP2
	GP3  = machine.GP3
	GP4  = machine.GP4
	GP5  = machine.GP5
	GP6  = machine.GP6
	GP7  = machine.GP7
	GP8  = machine.GP8
	GP9  = machine.GP9
	GP10 = machine.GP10
	GP11 = machine.GP11
	GP12 = machine.GP12
	GP13 = machine.GP13
	GP14 = machine.GP14
	GP15 = machine.GP15
	GP16 = machine.GP16
	GP17 = machine.GP17
	GP18 = machine.GP18
	GP19 = machine.GP19
	GP20 = machine.GP20
	GP21 = machine.GP21
	GP22 = machine.GP22
	GP26 = machine.GP26
	GP27 = machine.GP27
	GP28 = machine.GP28

	PinInput         = machine.PinInput
	PinOutput        = machine.PinOutput
	PinInputPullup   = machine.PinInputPullup
	PinInputPulldown = machine.PinInputPulldown
)

func InitADC() {
	// InitADC resets the ADC peripheral.
	machine.InitADC()
}
