echo "// Code generated by $0; DO NOT EDIT." > machine_emulated.go
sed -e 's,//go:build pico,//go:build !baremetal,' \
    -e 's,import "machine",import machine "gbenson.net/go/picosynth/x/emulator",' \
    < machine_pico.go \
    >> machine_emulated.go
