import sys

from dataclasses import dataclass
from functools import partial


# Legend Color  Key     KI      KO
TSV = """\
Song	Red	1	7	6
Stop	Purple	2	5	5
Rhythm	Yellow	3	2	5
Accomp.	Yellow	4	3	5
Funny	Yellow	5	4	5
Keyboard	Green	6	0	4
Wind	Green	7	1	4
String	Green	8	2	4
Synth	Green	9	3	4
S.E.	Green	0	4	4
Tone Edit	Green	Backspace	7	4

C#4	Black	w	0	1
D#4	Black	e	2	1
F#4	Black	t	5	1
G#4	Black	y	7	1
A#4	Black	u	1	2
C#5	Black	o	4	2
D#5	Black	p	6	2
F#5	Black	Right bracket	1	3
G#4	Black	Return	3	3

C4	White	a	7	0
D4	White	s	1	1
E4	White	d	3	1
F4	White	f	4	1
G4	White	g	6	1
A4	White	h	0	2
B4	White	j	2	2
C5	White	k	3	2
D5	White	l	5	2
E5	White	Semicolon	7	2
F5	White	Quote	0	3
G5	White	Hash	2	3

-	Orange	z	6	5
+	Orange	x	5	4
-	Purple	c	7	5
+	Purple	v	6	4"""


@dataclass
class SoftKey:
    _text: str
    _color: str
    _code: str
    _ki: str
    _ko: str

    def attrs(self):
        if not self.is_note:
            yield "Legend", f'"{self._text}"'
        yield "Color", self.color.title()
        match (code := self.code):
            case "K_BACKSPACE":
                yield "Offset", 2
                yield "Wide", "true"
            case "K_t":
                yield "Offset", 1
            case "K_o":
                yield "Offset", 1
            case "K_RIGHTBRACKET":
                yield "Offset", 1
        yield "KI", int(self._ki)
        yield "KO", int(self._ko)
        yield "Name", f'"{self.key}"'
        yield "Code", f"sdl.{code}"

    @property
    def code(self) -> str:
        code = self._code
        if len(code) > 1:
            code = "".join(code.split()).upper()
        return f"K_{code}"

    @property
    def key(self):
        key = self.code.removeprefix("K_")
        if len(key) == 1:
            return key.upper()
        key = key.lower().title()
        return {
            "Backspace": "BKSP",
            "Hash": "#",
            "Quote": "'",
            "Return": "Ret",
            "Rightbracket": "]",
            "Semicolon": ";",
        }.get(key, key)

    @property
    def color(self) -> str:
        return self._color.lower()

    @property
    def is_note(self) -> bool:
        return self.color in ("white", "black")

    @property
    def note(self) -> str:
        if self.is_note:
            return self._text


rows = [[]]
for line in TSV.split("\n"):
    if not line:
        rows.append([])
        continue
    rows[-1].append(SoftKey(*line.split("\t")))

command = " ".join(["python"] + sys.argv)
with open("keyboard-layout.go", "w") as fp:
    print = partial(print, file=fp)
    print(f"// Code generated by {command}; DO NOT EDIT.")
    print()
    print("package sdl")
    print()
    print('import "github.com/veandco/go-sdl2/sdl"')
    print()
    print("var keyboardLayout = [][]SoftKey{")
    for row in rows:
        print("\t[]SoftKey{")
        for keydef in row:
            print("\t\tSoftKey{")
            if (is_note := keydef.is_note):
                print(f"\t\t\t// {keydef.note}")
            attrs = dict(keydef.attrs())
            has_offset = "Offset" in attrs
            for attr, value in attrs.items():
                line = f"\t\t\t{attr + ':':7} {value},"
                if is_note and not has_offset:
                    line = line.replace(": ", ":")
                print(line)
            print("\t\t},")
        print("\t},")
    print("}")
