// Code generated by python make-keyboard-layout.py; DO NOT EDIT.

package emulator

import "github.com/veandco/go-sdl2/sdl"

var keyboardLayout = [][]SoftKey{
	[]SoftKey{
		SoftKey{
			Legend: "Song",
			Color:  Red,
			KI:     7,
			KO:     6,
			Name:   "1",
			Code:   sdl.K_1,
		},
		SoftKey{
			Legend: "Stop",
			Color:  Purple,
			KI:     5,
			KO:     5,
			Name:   "2",
			Code:   sdl.K_2,
		},
		SoftKey{
			Legend: "Rhythm",
			Color:  Yellow,
			KI:     2,
			KO:     5,
			Name:   "3",
			Code:   sdl.K_3,
		},
		SoftKey{
			Legend: "Accomp.",
			Color:  Yellow,
			KI:     3,
			KO:     5,
			Name:   "4",
			Code:   sdl.K_4,
		},
		SoftKey{
			Legend: "Funny",
			Color:  Yellow,
			KI:     4,
			KO:     5,
			Name:   "5",
			Code:   sdl.K_5,
		},
		SoftKey{
			Legend: "Keyboard",
			Color:  Green,
			KI:     0,
			KO:     4,
			Name:   "6",
			Code:   sdl.K_6,
		},
		SoftKey{
			Legend: "Wind",
			Color:  Green,
			KI:     1,
			KO:     4,
			Name:   "7",
			Code:   sdl.K_7,
		},
		SoftKey{
			Legend: "String",
			Color:  Green,
			KI:     2,
			KO:     4,
			Name:   "8",
			Code:   sdl.K_8,
		},
		SoftKey{
			Legend: "Synth",
			Color:  Green,
			KI:     3,
			KO:     4,
			Name:   "9",
			Code:   sdl.K_9,
		},
		SoftKey{
			Legend: "S.E.",
			Color:  Green,
			KI:     4,
			KO:     4,
			Name:   "0",
			Code:   sdl.K_0,
		},
		SoftKey{
			Legend: "Tone Edit",
			Color:  Green,
			Offset: 2,
			Wide:   true,
			KI:     7,
			KO:     4,
			Name:   "BKSP",
			Code:   sdl.K_BACKSPACE,
		},
	},
	[]SoftKey{
		SoftKey{
			// C#4
			Color: Black,
			KI:    0,
			KO:    1,
			Name:  "W",
			Code:  sdl.K_w,
		},
		SoftKey{
			// D#4
			Color: Black,
			KI:    2,
			KO:    1,
			Name:  "E",
			Code:  sdl.K_e,
		},
		SoftKey{
			// F#4
			Color:  Black,
			Offset: 1,
			KI:     5,
			KO:     1,
			Name:   "T",
			Code:   sdl.K_t,
		},
		SoftKey{
			// G#4
			Color: Black,
			KI:    7,
			KO:    1,
			Name:  "Y",
			Code:  sdl.K_y,
		},
		SoftKey{
			// A#4
			Color: Black,
			KI:    1,
			KO:    2,
			Name:  "U",
			Code:  sdl.K_u,
		},
		SoftKey{
			// C#5
			Color:  Black,
			Offset: 1,
			KI:     4,
			KO:     2,
			Name:   "O",
			Code:   sdl.K_o,
		},
		SoftKey{
			// D#5
			Color: Black,
			KI:    6,
			KO:    2,
			Name:  "P",
			Code:  sdl.K_p,
		},
		SoftKey{
			// F#5
			Color:  Black,
			Offset: 1,
			KI:     1,
			KO:     3,
			Name:   "]",
			Code:   sdl.K_RIGHTBRACKET,
		},
		SoftKey{
			// G#4
			Color: Black,
			KI:    3,
			KO:    3,
			Name:  "Ret",
			Code:  sdl.K_RETURN,
		},
	},
	[]SoftKey{
		SoftKey{
			// C4
			Color: White,
			KI:    7,
			KO:    0,
			Name:  "A",
			Code:  sdl.K_a,
		},
		SoftKey{
			// D4
			Color: White,
			KI:    1,
			KO:    1,
			Name:  "S",
			Code:  sdl.K_s,
		},
		SoftKey{
			// E4
			Color: White,
			KI:    3,
			KO:    1,
			Name:  "D",
			Code:  sdl.K_d,
		},
		SoftKey{
			// F4
			Color: White,
			KI:    4,
			KO:    1,
			Name:  "F",
			Code:  sdl.K_f,
		},
		SoftKey{
			// G4
			Color: White,
			KI:    6,
			KO:    1,
			Name:  "G",
			Code:  sdl.K_g,
		},
		SoftKey{
			// A4
			Color: White,
			KI:    0,
			KO:    2,
			Name:  "H",
			Code:  sdl.K_h,
		},
		SoftKey{
			// B4
			Color: White,
			KI:    2,
			KO:    2,
			Name:  "J",
			Code:  sdl.K_j,
		},
		SoftKey{
			// C5
			Color: White,
			KI:    3,
			KO:    2,
			Name:  "K",
			Code:  sdl.K_k,
		},
		SoftKey{
			// D5
			Color: White,
			KI:    5,
			KO:    2,
			Name:  "L",
			Code:  sdl.K_l,
		},
		SoftKey{
			// E5
			Color: White,
			KI:    7,
			KO:    2,
			Name:  ";",
			Code:  sdl.K_SEMICOLON,
		},
		SoftKey{
			// F5
			Color: White,
			KI:    0,
			KO:    3,
			Name:  "'",
			Code:  sdl.K_QUOTE,
		},
		SoftKey{
			// G5
			Color: White,
			KI:    2,
			KO:    3,
			Name:  "#",
			Code:  sdl.K_HASH,
		},
	},
	[]SoftKey{
		SoftKey{
			Legend: "-",
			Color:  Orange,
			KI:     6,
			KO:     5,
			Name:   "Z",
			Code:   sdl.K_z,
		},
		SoftKey{
			Legend: "+",
			Color:  Orange,
			KI:     5,
			KO:     4,
			Name:   "X",
			Code:   sdl.K_x,
		},
		SoftKey{
			Legend: "-",
			Color:  Purple,
			KI:     7,
			KO:     5,
			Name:   "C",
			Code:   sdl.K_c,
		},
		SoftKey{
			Legend: "+",
			Color:  Purple,
			KI:     6,
			KO:     4,
			Name:   "V",
			Code:   sdl.K_v,
		},
	},
}
