package fmt

type Int32 interface {
	~int | ~int32 | ~uint | ~uint32 | uintptr
}

var hexDigits = []byte("0123456789abcdef")

// AppendHex32 appends the string form of the 32-bit unsigned integer
// i, as generated by [Hex32], to dst and returns the extended buffer.
func AppendHex32[T Int32](dst []byte, i T) []byte {
	v := uint32(i)
	var buf [8]byte
	for i := 7; i >= 0; i-- {
		buf[i] = hexDigits[v&15]
		v >>= 4
	}
	return append(dst, buf[:]...)
}

// Hex32 returns the string representation of i in base 16. The result
// uses the lower-case letters 'a' to 'f' for digit values >= 10 and
// is zero padded to eight digits wide.
func Hex32[T Int32](i T) string {
	return string(AppendHex32(nil, i))
}

// Hex32Stringer is equivalent to fmt.Sprintf("%s(0x%08x)", name, uint32(i)).
func Hex32Stringer[T Int32](name string, i T) string {
	// Frequency(0xcafebabe)
	//          11111111112222
	// 12345678901234567890123
	var buf [24]byte
	b := buf[:0]

	b = append(b, []byte(name)...)
	b = append(b, []byte("(0x")...)
	b = AppendHex32(b, i)
	b = append(b, ')')

	return string(b)
}
