echo "// Code generated by $0; DO NOT EDIT." > piolib_emulated.go
sed -e 's,//go:build pico,//go:build !baremetal,' \
    -e 's,"github.com/tinygo-org/pio/rp2-pio/piolib",piolib "gbenson.net/go/picosynth/x/emulator",' \
    < piolib_pico.go \
    >> piolib_emulated.go
